#application配置文件
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/online_exam?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    url: jdbc:mysql://localhost:3306/online_exams?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:mysql://8.219.62.142:3306/online_exams?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: user
    password: 123456
#    #druid数据源配置
#    druid:
#      # 初始化连接池大小
#      initialSize: 5
#      # 最小连接数
#      minIdle: 5
#      # 最大连接数
#      maxActive: 40
#      # 获取连接时的最大等待时间
#      maxWait: 60000
#      #间隔多长时间进行一次检测；
#      timeBetweenEvictionRunsMillis: 60000
#      #配置一个最小的生存对象的空闲时间
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1
#      testWhileIdle: true
#      #申请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
#      testOnBorrow: false
#      #归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能
#      testOnReturn: false
#      poolPreparedStatements: true
#      #配置监控统计拦截的filters。stat：监控统计、wall：防御sql注入、log4j：日志记录
#      filters: stat,log4j
#      maxPoolPreparedStatementPerConnectionSize: 20
#      useGlobalDataSourceStat: true
#      #执行时间超过3000毫秒的sql会被标记为慢sql
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
#      #配置过滤器，过滤掉静态文件
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: /druid/*,*.js,*.css,*.gif,*.jpg,*.bmp,*.png,*.ico
#      #配置可视化控制台页面
#      stat-view-servlet:
#        filter:
#          stat:
#            merge-sql: false
#        enabled: true
#        #访问德鲁伊监控页面的地址
#        url-pattern: /druid/*
#        #IP白名单 没有配置或者为空 则允许所有访问
#        allow: xxx.xxx.xxx
#        #IP黑名单 若白名单也存在 则优先使用
#        #deny: ip地址
#        #禁用重置按钮
#        reset-enable: true
#        #登录所用的用户名与密码
#        login-username: admin
#        login-password: 123456
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver    #JDBC驱动程序类名
#    url: jdbc:mysql://localhost:3306/online_exams?userUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    username: root
#    password: 123456
  jpa:
    database: MYSQL
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: localhost
    port: 6379
#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #配置逻辑删除
      logic-delete-value: 1 #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 #逻辑未删除值(默认为 0)




